apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  my.cnf: |
    [mysqld]
    bind-address=0.0.0.0    # Changed from "bind 0.0.0.0" to correct syntax
    port=3306
    default-storage-engine=InnoDB
    default_authentication_plugin = mysql_native_password  # REQUIRED for Go compatibility
  
  initdb.sql: |
    CREATE DATABASE IF NOT EXISTS emat;
    USE emat;

  createdb.sql: |
   
    -- Create products table (FIXED price column)
    CREATE TABLE IF NOT EXISTS products (
      id INT, 
      name VARCHAR(255), 
      price DOUBLE,  
      image VARCHAR(255), 
      category VARCHAR(255), 
      isNew BOOLEAN
    );
    
  insertdb.sql: | 

    -- Insert initial data
    INSERT IGNORE INTO products (id, name, price, image, category, isNew) VALUES 
      (1, 'Classic White T-Shirt', 29.99, 'blue.jpg', 'men', 0),
      (2, 'Jeans', 59.99, 'jeans.jpg', 'men', 1),
      (3, 'Summer Floral Dress', 9.99, 'dress.jpg', 'men', 0),
      (4, 'Casual Hoodie', 23.99, 'hoodie.jpg', 'men', 0),
      (5, 'Casual Hoodie', 30.99, 'blue.jpg', 'men', 1),
      (6, 'Pleated Skirt', 50.99, 'denim.jpg', 'men', 0),
      (7, 'Knit Sweater', 129.99, 'sweater.jpg', 'men', 1),
      (8, 'Cargo Pants', 160.99, 'cargo.jpg', 'men', 0);
    
    
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    port 6379
    