apiVersion: apps/v1
kind: Deployment
metadata:
  name: ematbackend
spec:
  selector:
    matchLabels:
      app: ematbackend
  template:
    metadata:
      labels:
        app: ematbackend
    spec:
      containers:
      - name: ematbackend
        image: haxor44/ematbackend:latest
        env:
        - name:  MYSQL_DSN 
          value: "root:@tcp(mysql-service:3306)/emat?parseTime=true"
        - name: REDIS_ADDR
          value:  "redis-service:6379"
        - name: REDIS_DB
          value: "0"
        resources:
          limits:
            memory: "600Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: ematbackend-service
spec:
  type: ClusterIP
  selector:
    app: ematbackend
  ports:    
    - name: ematbackend
      protocol: TCP
      port: 8080
      targetPort: 8080
      
    


