apiVersion: apps/v1
kind: Deployment
metadata:
  name: emat
spec:
  selector:
    matchLabels:
      app: emat
  template:
    metadata:
      labels:
        app: emat
    spec:
      containers:
      - name: emat
        image: haxor44/emats:latest
        env:
        - name: API_URL
          value: "http://ematbackend-service:8080"
        - name: NEXT_PUBLIC_API_BASE_PATH
          value: "/api/proxy"
        resources:
          limits:
            memory: "600Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: emat-frontend
spec:
  type: NodePort
  selector:
    app: emat
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30600
    
     
     

